# Numpy Part-2

In [5]:
import numpy as np

## 4. Operation

In [4]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [8]:
# 모든 요소들의 합
a.sum()

78

In [13]:
# 열 의 합 (axis 가 0일 때)
a.sum(axis=0)             

array([15, 18, 21, 24])

In [12]:
# 행의 합 (axis 가 1일 때)
a.sum(axis=1)

array([10, 26, 42])

In [14]:
np.sum(a[1])

26

In [15]:
a.min(axis=0)

array([1, 2, 3, 4])

In [18]:
a.max(axis=0)

array([ 9, 10, 11, 12])

In [20]:
a.mean()                # 평균

6.5

In [22]:
a.mean(axis=0), a.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

- Sorting

In [24]:
b = np.array([[4,3,5,7], [1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [33]:
np.sort(b)              # axis = 1, ascending order  (axis=1 이 default)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [28]:
np.sort(b, axis=0)

array([[ 1,  3,  1,  7],
       [ 2,  5,  5,  9],
       [ 4, 12, 11, 14]])

In [29]:
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [32]:
b.sort()                        # b.sort 를 한 후에는 b 값이 변경 됨.
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [34]:
b.sort(axis=0)
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [37]:
# 내림차순
c = np.array([42,38,12,25])
np.sort(c)[::-1]                        # 내림차순일때는 ::-1, 오름차순일때는 ::1

array([42, 38, 25, 12])

In [39]:
np.argsort(c)               # index 값을 나타냄

array([2, 3, 1, 0], dtype=int64)

In [40]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

In [41]:
indices = np.argsort(c)                 # 순서를 알고 싶을때
c[indices]

array([12, 25, 38, 42])

- Mathematical functions

In [46]:
# sigmoid 함수     
def sigmoid(x):
    return 1. / (1 + np.exp(-x))

In [47]:
X = np.array([-10,0,10])
sigmoid(X)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose (전치)

In [49]:
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [50]:
b. T

array([[ 1,  1,  3],
       [ 2,  4,  9],
       [ 5,  5, 11],
       [ 7, 12, 14]])

- concatenate, vstack, hstack               (어레이를 합치는 법)

In [53]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [55]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [57]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
np.hstack((a,b.T))          # b값을 돌린 후 옆으로 쌓음

array([[1, 2, 5],
       [3, 4, 6]])

In [67]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [69]:
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

## 5. Array Operation

- 사칙연산

In [72]:
a

array([[1, 2],
       [3, 4]])

In [73]:
a + a

array([[2, 4],
       [6, 8]])

In [74]:
a - a

array([[0, 0],
       [0, 0]])

In [75]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [76]:
a / a

array([[1., 1.],
       [1., 1.]])

In [77]:
a + 3               # 3의 값이 모든 element 에 더해짐

array([[4, 5],
       [6, 7]])

- dot product

In [82]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
b = np.arange(7,13).reshape(3,2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [85]:
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

In [86]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [88]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))                # 1차원일때는 범위가 같지않아도 곱해서 더해줌

32

## 6. Comparison

- all & any


In [90]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [92]:
np.any(a>5)                 # 하나라도 True 가 있으면 True

True

In [94]:
np.all(a>5)                 # 전부다 True 여야 True

False

- Logical operation

In [97]:
b = np.logical_and(a > 3, a < 7)            # 3보다 크고 7보다 작은 수
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [101]:
b = np.logical_or(a > 7, a < 3)             # 7보다 크거나 3보다 작은 수
b

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [103]:
a.argmax(), np.argmax(a)                # 두가지 방법 모두 사용 가능

(9, 9)

In [104]:
a.argmin(), np.argmin(a)

(0, 0)

## 7. Boolean & Fancy indexing

- boolean indexing

In [107]:
# array a 에서 값이 6 이상인 것만 가져오기 - Filtering
a[a >= 6]

array([6, 7, 8, 9])

In [108]:
a >= 6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [110]:
b

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

In [112]:
a[b]                        # b에서 True 값만 가져옴

array([0, 1, 2, 8, 9])

- fancy indexing

In [114]:
a = np.array([2,4,6,8])
b = np.array([0,0,1,3,2,1])                         # a의 인덱스값
a[b]                                                # 순서에 상응되는 값을 가져옴

array([2, 2, 4, 8, 6, 4])

## 8. 기술 통계

In [123]:
a = np.random.randn(10)
a

array([-2.07581826, -1.01921444,  1.61920071, -0.6857046 ,  1.83226964,
       -0.32417414,  0.97274306,  0.87327686, -1.15492777, -0.43687322])

In [124]:
# 평균
np.mean(a), a.mean()

(-0.03992221609143428, -0.03992221609143428)

In [125]:
# 표준편차 (standard deviation)
np.std(a), a.std()

(1.2296236104484164, 1.2296236104484164)

In [126]:
# 최소, 최대
a.min(), a.max()

(-2.075818262734122, 1.8322696354357724)

In [127]:
# 4분위수
np.percentile(a, 25), np.percentile(a, 50), np.percentile(a, 75)

(-0.9358369789167784, -0.3805236792807173, 0.9478765089765637)

In [128]:
# 중앙값
np.median(a)

-0.3805236792807173

In [130]:
a = np.random.randint(0, 3, 100)                    # 0 부터 3까지 100개
a

array([1, 2, 2, 2, 1, 1, 1, 1, 0, 2, 2, 2, 1, 1, 1, 0, 2, 1, 0, 0, 0, 2,
       2, 1, 2, 1, 2, 0, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1,
       1, 1, 2, 1, 2, 1, 1, 2, 1, 0, 0, 1, 1, 2, 0, 2, 0, 1, 0, 1, 0, 0,
       0, 1, 2, 1, 2, 1, 2, 1, 0, 0, 2, 1, 0, 1, 2, 2, 2, 0, 1, 2, 1, 2,
       1, 0, 0, 2, 2, 0, 1, 2, 2, 1, 0, 1])

In [131]:
# 0, 1, 2 의 갯수 구하기
np.unique(a)                # 값만 가져옴

array([0, 1, 2])

In [133]:
np.unique(a, return_counts=True)        # 0,1,2의 갯수를 가져옴

(array([0, 1, 2]), array([25, 41, 34], dtype=int64))